replicaCount: 2

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

workloadIdentity:
  clientId: "4ed244e9-2aa9-46bc-bb1c-7f5c9949a2d1" # TODO: set from terraform output -raw mi_processor_service_client_id

serviceAccount:
  name: processor-service

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

nodeSelector:
  nodepool-type: workload

podDisruptionBudget:
  minAvailable: 1

