replicaCount: 2

image:
  repository: "" 
  tag: "latest"
  pullPolicy: Always


workloadIdentity:
  clientId: "" 

serviceAccount:
  name: api-service

processorUrl: "http://processor-service"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
  host: "" 
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

nodeSelector:
  nodepool-type: workload

podDisruptionBudget:
  minAvailable: 1